#PBS -lwalltime=2:00:00
#PBS -lnodes=1 
#PBS -S /bin/bash
#PBS -N profile
#PBS -j oe
#PBS -o /home/armartin/pgc_scz_asia/imp_collect/prs_score/armartin/logs
#PBS -t 1-14

module load plink2

FILE=`sed "${PBS_ARRAYID}q;d" /home/armartin/pgc_scz_asia/imp_collect/prs_score/armartin/prefixes.txt`
BASE=`basename $FILE`
DIR=`dirname $FILE`

SCORE_DIR=`dirname $SCORE_BASE`
#/home/armartin/pgc_scz_asia/imp_collect/prs_score/armartin/mtag/sigma0

#2. Make SCZ PRS, scoring clumped variants only
plink --bfile ${FILE} \
--extract ${SCORE_BASE}.clumped.mhc \
--q-score-range /home/armartin/pgc_scz_asia/imp_collect/prs_score/armartin/score_range.txt ${SCORE_BASE}.txt 1 12 header \
--score ${SCORE_BASE}.txt 1 4 9 \
--out ${SCORE_DIR}/${BASE}
